### ISSUE TITLE
Upgrade to the latest?

### ISSUE THREAD

**Issue by reinethernal** [marc-romu/home-assistant_blueprints#1]
Hey Marc!
First of all, thanks for such cool blueprints!
Second, will you be able to update them to support the latest version?

**Comment by marc-romu** [comment]
Sure! Which new features do you expect?

**Comment by reinethernal** [comment]
Correctly working as before update :)
When i try to run menu item, or submenu, i receive 
`Error executing script. Invalid data for call_service at pos 2: expected int @ data['target'][0]`

I found that on one of the latest updates they made changes like:
The send.message service now has a target.
In edit.message service target was removed in the update.

https://www.home-assistant.io/integrations/telegram_bot/

**Comment by marc-romu** [comment]
In which blueprint do you experience this error?

**Comment by marc-romu** [comment]
Ok, I think it has to do with this issue on `telegram_bot` integration. https://github.com/home-assistant/core/issues/70232
I close this one as it is not a problem with the blueprint itself.
However, thanks for reporting!

**Comment by marc-romu** [comment]
I just updated the automation blueprints to avoid using data that is causing the error. This means that variables `telegram_sender_first_name`, `telegram_sender_last_name`, `telegram_sender_full_name` and `telegram_sender_user_id` are now only available if you call a command (when you type /command in a telegram text message). If you click an inline keyboard button, these variables will not work. "Reply in private" function will only work with commands too.
